frontend:
  - changed-files:
      - any-glob-match-pattern: 'frontend/**'

backend:
  - changed-files:
      - any-glob-match-pattern: 'backend/**'

documentation:
  - changed-files:
      - any-glob-match-pattern: 'docs/**'
